spring.application.name=task-manager

server.port=8088


#jpa
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.name=tasks
spring.datasource.password=root19
spring.datasource.username=postgres
